### PR TITLE
a new commit message has been added from nmrony/gtni

### PR DESCRIPTION
**Pull request by nurrony**
Added a new commit message from one of my projects called gtni. 

[Commit Link](https://github.com/nmrony/gtni/commit/74317fde9c8f3bbd6e67edf55bb3ce8b2c562611)

### CODE REVIEW

**Comment by nmrony** [comment]
Does this project maintain anymore?

**Comment by ycombinator** [comment]
Sorry @nmrony, I wasn't getting notifications for PRs! Your PR looks good but there are merge conflicts at the moment. Do you mind rebasing against master? I'll merge it as soon as that's done.

**Comment by nurrony** [comment]
@ycombinator Sure.. Don't worry I will rebase it against mater when I manage some time for it and notify you. 

Thanks

**Comment by luislobo** [comment]
😆

**Comment by luislobo** [comment]
🤣

**Comment by nurrony** [comment]
closing this in favor of https://github.com/ycombinator/funny-commit-messages/pull/9

**Pull request closed without merging**
